### ISSUE TITLE
A0-2962: Dockerfile

### ISSUE THREAD

**Issue by mgralinski-bright** [Cardinal-Cryptography/ink-wrapper#51]
I was trying to create a docker file where I could run `ink-wrapper`. For reasons unknown to me, ink-wrapper produces wrong output. I am attaching [sample.zip](https://github.com/Cardinal-Cryptography/ink-wrapper/files/12248336/test.zip) where you will find everything to reproduce the issue.

**Comment by obrok** [comment]
Thanks for the report, I'll look into it!

**Comment by obrok** [comment]
The problem seems to be with the version of rust you're using to install `ink-wrapper`. I believe this is related to an issue in a dependency of the library we use for code generation and the API it depends on, which is now being changed in nightly rust (https://github.com/udoprog/genco/issues/39). For now, I'd recommend installing with:

```bash
cargo +nightly-2023-04-16 install ink-wrapper --locked --version 0.5.0
```

to basically lock the toolchain you're using to compile `ink-wrapper` to one that's known to work (I checked, and this one indeed works). I'll add a note about this to the README, and in the future, I hope the relevant changes will just be released into rust proper, so we can set min rust version and it will just work automatically or fail with an appropriate message.

**Comment by mgralinski-bright** [comment]
Installing `ink-wrapper` with fixed version `nightly-2023-04-16`, solved the issue. Thanks!
